### ISSUE TITLE
运行 run_ui.py出现的报错

### ISSUE THREAD

**Issue by dondon03-10** [HPCL-EI/RoboWaiter#3]
**问题描述**
在运行 run_ui.py时，报错：ImportError: DLL load failed while importing GrabSim_pb2: 找不到指定的模块。

**代码示例**
```
F:\RoboWaiter>python run_ui.py
Traceback (most recent call last):
  File "F:\RoboWaiter\run_ui.py", line 1, in <module>
    from robowaiter.scene.ui.pyqt5 import UI
  File "F:\RoboWaiter\robowaiter\scene\ui\pyqt5.py", line 19, in <module>
    from robowaiter.scene.ui.scene_ui import SceneUI
  File "F:\RoboWaiter\robowaiter\scene\ui\scene_ui.py", line 13, in <module>
    from robowaiter.scene.scene import Scene
  File "F:\RoboWaiter\robowaiter\scene\scene.py", line 11, in <module>
    from robowaiter.proto import camera
  File "F:\RoboWaiter\robowaiter\proto\__init__.py", line 1, in <module>
    from . import GrabSim_pb2
ImportError: DLL load failed while importing GrabSim_pb2: 找不到指定的模块。
```

**Comment by Caiyishuai** [comment]
看看是不是python版本问题，Python=3.10。如果再不行，可以把from . import GrabSim_pb2改为绝对路径试试，可能是路径不对找不到。GrabSim_pb2_grpc.pyd 和 GrabSim_pb2.pyd 是两个文件，默认是在\RoboWaiter\robowaiter\proto下面，你可以移动它们。

**Comment by dondon03-10** [comment]
将python版本切换为3.10后安装robowaiter软件包会报错，ERROR: Package 'robowaiter' requires a different Python: 3.10.14 not in '<4.0,>=3.11'

```
(python3.10) F:\RoboWaiter>pip install -e .
Obtaining file:///F:/RoboWaiter
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of robowaiter to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'robowaiter' requires a different Python: 3.10.14 not in '<4.0,>=3.11'
```
```
(python3.10) F:\RoboWaiter>python --version
Python 3.10.14
```

**Comment by dondon03-10** [comment]
通过修改pyproject文件中的python版本解决了问题，我为可能带来的不便感到抱歉。
