### ISSUE TITLE
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by ovjust** [HPCL-EI/RoboWaiter#8]
启动ui后 就报这个错。

Traceback (most recent call last):
  File "D:\1MyFiles\code\python\RoboWaiter\robowaiter\scene\ui\pyqt5.py", line 37, in run
    self.scene = self.task(self.scene_cls,self.robot_cls,self.scene_queue,self.ui_queue)
  File "D:\1MyFiles\code\python\RoboWaiter\robowaiter\scene\ui\pyqt5.py", line 50, in run_scene
    scene.reset()
  File "D:\1MyFiles\code\python\RoboWaiter\robowaiter\scene\scene.py", line 460, in reset
    self.init_robot()
  File "D:\1MyFiles\code\python\RoboWaiter\robowaiter\scene\ui\scene_ui.py", line 377, in init_robot       
    self.robot.load_BT()
  File "D:\1MyFiles\code\python\RoboWaiter\robowaiter\robot\robot.py", line 44, in load_BT
    self.bt = load_bt_from_ptml(self.scene, self.ptml_path,self.behavior_lib_path)
  File "D:\1MyFiles\code\python\RoboWaiter\robowaiter\utils\bt\load.py", line 8, in load_bt_from_ptml      
    ptml_bt = ptmlCompiler.load(scene, ptml_path, behavior_lib_path)
  File "D:\1MyFiles\code\python\RoboWaiter\robowaiter\behavior_tree\ptml\ptmlCompiler.py", line 51, in load
    walker.walk(ptml, tree)
  File "C:\Users\kun-hp\.conda\envs\RoboWaiter\lib\site-packages\antlr4\tree\Tree.py", line 160, in walk   
    self.walk(listener, child)
  File "C:\Users\kun-hp\.conda\envs\RoboWaiter\lib\site-packages\antlr4\tree\Tree.py", line 160, in walk   
    self.walk(listener, child)
  File "C:\Users\kun-hp\.conda\envs\RoboWaiter\lib\site-packages\antlr4\tree\Tree.py", line 160, in walk   
    self.walk(listener, child)
  File "C:\Users\kun-hp\.conda\envs\RoboWaiter\lib\site-packages\antlr4\tree\Tree.py", line 158, in walk   
    self.enterRule(listener, t)
  File "C:\Users\kun-hp\.conda\envs\RoboWaiter\lib\site-packages\antlr4\tree\Tree.py", line 178, in enterRule
    ctx.enterRule(listener)
  File "D:\1MyFiles\code\python\RoboWaiter\robowaiter\behavior_tree\ptml\ptmlParser.py", line 321, in enterRule
    listener.enterAction_sign(self)
  File "D:\1MyFiles\code\python\RoboWaiter\robowaiter\behavior_tree\ptml\ptmlTranslator.py", line 95, in enterAction_sign
    exec(f"from {name} import {name}")
  File "<string>", line 1, in <module>
  File "D:\1MyFiles\code\python\RoboWaiter\robowaiter/behavior_lib\act\DealChat.py", line 17, in <module>  
    import spacy
  File "C:\Users\kun-hp\.conda\envs\RoboWaiter\lib\site-packages\spacy\__init__.py", line 6, in <module>   
    from .errors import setup_default_warnings
  File "C:\Users\kun-hp\.conda\envs\RoboWaiter\lib\site-packages\spacy\errors.py", line 3, in <module>     
    from .compat import Literal
  File "C:\Users\kun-hp\.conda\envs\RoboWaiter\lib\site-packages\spacy\compat.py", line 39, in <module>    
    from thinc.api import Optimizer  # noqa: F401
  File "C:\Users\kun-hp\.conda\envs\RoboWaiter\lib\site-packages\thinc\api.py", line 1, in <module>        
    from .backends import (
  File "C:\Users\kun-hp\.conda\envs\RoboWaiter\lib\site-packages\thinc\backends\__init__.py", line 17, in <module>
    from .cupy_ops import CupyOps
  File "C:\Users\kun-hp\.conda\envs\RoboWaiter\lib\site-packages\thinc\backends\cupy_ops.py", line 16, in <module>
    from .numpy_ops import NumpyOps
  File "thinc\backends\numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by ovjust** [comment]
模拟器是机器人的第一视角吗？  除了强退，按什么键退出？
